# Generated by Django 6.0.7 on 2026-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('soiltype', models.CharField(max_length=200)),
                ('sowingmonth', models.CharField(max_length=200)),
                ('harvestingmonth', models.CharField(max_length=200)),
                ('fertilizer', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
            ],
        ),
    ]
