# Generated by Django 6.0.7 on 2026-07-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=200)),
                ('marketname', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
