# Generated by Django 6.0.7 on 2026-07-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_marketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField()),
                ('village', models.CharField(max_length=200)),
                ('taluka', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
    ]
