# Generated by Django 6.0.7 on 2026-07-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_government'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('taluka', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('cropdetails', models.CharField(max_length=200)),
            ],
        ),
    ]
